version: '3.8'

services:
  mlflow:
    image: python:3.9
    command: >
      sh -c "pip install mlflow psycopg2-binary boto3 &&
      mlflow server --host 0.0.0.0 --port 5000
      --backend-store-uri postgresql://postgres:postgres@db/mlflow
      --default-artifact-root s3://mlflow-artifacts
      --serve-artifacts"
    ports:
      - "5000:5000"
    environment:
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=minio123
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
    depends_on:
      - db
      - minio

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mlflow
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    command: server /data
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    ports:
      - "9000:9000"  
      - "9001:9001"  
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data: